-- SQL Code that created the tables for my database

CREATE TABLE CATEGORIES (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(30) UNIQUE);

CREATE TABLE ITEM_IMAGES (ID INT AUTO_INCREMENT PRIMARY KEY, URL TEXT);

CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(30) NOT NULL UNIQUE, EMAIL VARCHAR(50) NOT NULL UNIQUE, PASSWORD VARCHAR(30) NOT NULL);

CREATE TABLE ITEMS (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(100) NOT NULL UNIQUE, CATEGORY_ID INT, ITEM_IMAGE_ID INT, CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID), CONSTRAINT FK_ITEM_IMAGE FOREIGN KEY (ITEM_IMAGE_ID) REFERENCES ITEM_IMAGES(ID));

CREATE TABLE LISTINGS (ID INT AUTO_INCREMENT PRIMARY KEY, USER_ID INT NOT NULL, ITEM_ID INT NOT NULL, PRICE DOUBLE NOT NULL, QUANTITY INT, CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID), CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID));

select l.id, u.username, i.name, l.price, c.name as category, ii.url from listings l join users u on l.user_id = u.id join items i on l.item_id = i.id join item_images ii on i.item_image_id = ii.id join categories c on i.category_id = c.id;