DROP TABLE USERS;
DROP TABLE ITEMS;
DROP TABLE CATEGORIES;

CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(30) NOT NULL UNIQUE, EMAIL VARCHAR(50) NOT NULL UNIQUE, PASSWORD VARCHAR(30) NOT NULL);

CREATE TABLE CATEGORIES (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(30) UNIQUE);

CREATE TABLE ITEMS (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(50) NOT NULL UNIQUE, CATEGORY_ID INT, CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID));

SELECT * FROM USERS;
SELECT * FROM CATEGORIES;
SELECT * FROM ITEMS;